<?php
echo <<<EOT
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{$service} | Online API Detail Document | PhalApi </title>

    <link rel="stylesheet" href="https://staticfile.qnssl.com/semantic-ui/2.1.6/semantic.min.css">
    <link rel="stylesheet" href="https://staticfile.qnssl.com/semantic-ui/2.1.6/components/table.min.css">
    <link rel="stylesheet" href="https://staticfile.qnssl.com/semantic-ui/2.1.6/components/container.min.css">
    <link rel="stylesheet" href="https://staticfile.qnssl.com/semantic-ui/2.1.6/components/message.min.css">
    <link rel="stylesheet" href="https://staticfile.qnssl.com/semantic-ui/2.1.6/components/label.min.css">

</head>

<body>

<br /> 

    <div class="ui text container" style="max-width: none !important;">
        <div class="ui floating message">

EOT;

echo "<h2 class='ui header'>API：$service</h2><br/> <span class='ui teal tag label'>$description</span>";

/**
 * API description & params
 */
echo <<<EOT
            <div class="ui raised segment">
                <span class="ui red ribbon label">DECRIPTION</span>
                <div class="ui message">
                    <p>{$descComment}</p>
                </div>
            </div>
            <h3>PARAMETERS</h3>
            <table class="ui red celled striped table" >
                <thead>
                    <tr><th>Parameter</th><th>Type</th><th>Required</th><th>Default</th><th>Note</th><th>Desc</th></tr>
                </thead>
                <tbody>
EOT;

foreach ($rules as $key => $rule) {
    $name = $rule['name'];
    if (!isset($rule['type'])) {
        $rule['type'] = 'string';
    }
    $type = isset($typeMaps[$rule['type']]) ? $typeMaps[$rule['type']] : $rule['type'];
    $require = isset($rule['require']) && $rule['require'] ? '<font color="red">Required</font>' : 'Optional';
    $default = isset($rule['default']) ? $rule['default'] : '';
    if ($default === NULL) {
        $default = 'NULL';
    } else if (is_array($default)) {
        $default = json_encode($default);
    } else if (!is_string($default)) {
        $default = var_export($default, true);
    }

    $other = array();
    if (isset($rule['min'])) {
        $other[] = ' Min: ' . $rule['min'];
    }
    if (isset($rule['max'])) {
        $other[] = ' Max: ' . $rule['max'];
    }
    if (isset($rule['range'])) {
        $other[] = ' Range: ' . implode('/', $rule['range']);
    }
    if (isset($rule['source'])) {
        $other[] = 'Source：' . strtoupper($rule['source']);
    }
    $other = implode('；', $other);

    $desc = isset($rule['desc']) ? trim($rule['desc']) : '';

    echo "<tr><td>$name</td><td>$type</td><td>$require</td><td>$default</td><td>$other</td><td>$desc</td></tr>\n";
}

/**
 * API Reponse
 */
echo <<<EOT
                </tbody>
            </table>
            <h3>RESPONSE</h3>
            <table class="ui green celled striped table" >
                <thead>
                    <tr><th>Filed</th><th>Type</th><th>Desc</th></tr>
                </thead>
                <tbody>
EOT;

foreach ($returns as $item) {
	$name = $item[1];
	$type = isset($typeMaps[$item[0]]) ? $typeMaps[$item[0]] : $item[0];
	$detail = $item[2];
	
	echo "<tr><td>$name</td><td>$type</td><td>$detail</td></tr>";
}

echo <<<EOT
            </tbody>
        </table>
EOT;

/**
 * Exception
 */
if (!empty($exceptions)) {
    echo <<<EOT
            <h3>EXCEPTION</h3>
            <table class="ui red celled striped table" >
                <thead>
                    <tr><th>Code</th><th>Message</th>
                </thead>
                <tbody>
EOT;

    foreach ($exceptions as $exItem) {
        $exCode = $exItem[0];
        $exMsg = isset($exItem[1]) ? $exItem[1] : '';
        echo "<tr><td>$exCode</td><td>$exMsg</td></tr>";
    }

    echo <<<EOT
            </tbody>
        </table>
EOT;
}

/**
 * Footer
 */
$version = PHALAPI_VERSION;
echo <<<EOT
        <div class="ui blue message">
          <strong>NOTE: </strong> This document is generated by PhalApi automatically. You can modify param ?service= as you want.
        </div>
        <p>&copy; Powered  By <a href="http://www.phalapi.net/" target="_blank">PhalApi {$version}</a> <p>
        </div>
    </div>
</body>
</html>
EOT;


